# Generated by Django 2.2.7 on 2019-12-01 21:23

from django.db import migrations, models
import django.db.models.deletion
import searchsite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('DOB', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=30, unique=True)),
                ('dateFounded', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('librarian_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('library_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchsite.Library')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_ID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255, null=True)),
                ('genre', models.CharField(choices=[('Non-Fiction', 'non-fiction'), ('Children', 'children'), ('Drama', 'drama'), ('Fantasy', 'fantasy'), ('Graphic Novel', 'graphic novel'), ('Horror', 'horror'), ('Mystery', 'mystery'), ('Poetry', 'poetry'), ('Romance', 'romance'), ('Satire', 'satire'), ('Biography', 'biography'), ('Auto-Biography', 'auto-biography'), ('Thriller', 'thriller'), ('Young Adult', 'young adult'), ('other', 'other')], default='other', max_length=18, validators=[searchsite.models.validate_genre])),
                ('datePublished', models.DateField(null=True)),
                ('publisher_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchsite.Publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Written_By',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchsite.Author')),
                ('book_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchsite.Book')),
            ],
            options={
                'unique_together': {('book_ID', 'author_ID')},
            },
        ),
        migrations.CreateModel(
            name='Library_Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(validators=[searchsite.models.validate_count])),
                ('book_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchsite.Book')),
                ('library_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchsite.Library')),
            ],
            options={
                'unique_together': {('library_name', 'book_ID')},
            },
        ),
        migrations.CreateModel(
            name='Librarian_Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('Non-Fiction', 'non-fiction'), ('Children', 'children'), ('Drama', 'drama'), ('Fantasy', 'fantasy'), ('Graphic Novel', 'graphic novel'), ('Horror', 'horror'), ('Mystery', 'mystery'), ('Poetry', 'poetry'), ('Romance', 'romance'), ('Satire', 'satire'), ('Biography', 'biography'), ('Auto-Biography', 'auto-biography'), ('Thriller', 'thriller'), ('Young Adult', 'young adult'), ('other', 'other')], default='other', max_length=18, validators=[searchsite.models.validate_genre])),
                ('librarian_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchsite.Librarian')),
            ],
            options={
                'unique_together': {('librarian_ID', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='Checks_Out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.DateField()),
                ('book_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchsite.Book')),
                ('library_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchsite.Library')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchsite.User')),
            ],
            options={
                'unique_together': {('user_ID', 'book_ID', 'library_name')},
            },
        ),
    ]
